# Generated by Django 6.0.3 on 2026-03-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colleges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
